### ISSUE TITLE
Question regarding your MatrixMulExample

### ISSUE THREAD

**Issue by jiatao99** [deepakkumar1984/Amplifier.NET#13]
I am confused of your MatrixMulExample. You are calling SGEMMKernals passing 2 input arrays and an output array. How does GPU parallel loop the array? Based on first one or both?

The output array contains all value set to 120.

If it based on both, how to control only loop one of them (another one is for lookup value)?

Thanks

**Comment by deepakkumar1984** [comment]
You probably need to understand how GPU computing works, because based on that understanding you need to write kernels.
