### ISSUE TITLE
Cannot use Math.PI

### ISSUE THREAD

**Issue by optimus-code** [deepakkumar1984/Amplifier.NET#17]
Hi, when I tried to use Math.PI it complained Math was unavailable. If I put the pure constant value of PI it gets replaced by the parser code with "Math.PI" code which means I have to define a dynamic variable to pass in a common constant. I believe in this case PI should just be output by the parser as its pure value.

**Comment by deepakkumar1984** [comment]
I guess need to fix an issue with the parser, will look into it this week.

**Comment by deepakkumar1984** [comment]
@optimus-code Added built-in constants which should be used
![image](https://user-images.githubusercontent.com/6328361/134825943-3b864898-9a4c-4486-bf06-16934e2623e0.png)

As per doc: https://manpages.debian.org/buster/opencl-1.2-man-doc/mathConstants.3clc.en.html

![image](https://user-images.githubusercontent.com/6328361/134825963-5877df14-620f-4031-a23b-de50c32ce62e.png)

I have to add all of them which I will be doing. Please take the latest code to test
