### ISSUE TITLE
No way to set a __constant or __local parameters for the kernel

### ISSUE THREAD

**Issue by Drejzer** [deepakkumar1984/Amplifier.NET#21]
As far as I can see, there is no way to declare a constant/local array parameter for the kernel.

No attributes in the kernel declaration results in an error satin that all pointers must be either __global, __constant or __local.

The docs do not mention anything, and there doesn't seem to be an equivalent attribute for the second and third of the above-mentioned kinds.

**Comment by deepakkumar1984** [comment]
I have added the [Local] and [Constant] kernel attribute which you can start using it with latest code and nuget package
